# Set build constants to be read by mkversion.cmd

# Product name
PRODUCTNAME = REXX Utilities - rexxutil replacement for eComStation

# Full UNIAUD build version
# BUILDVERSION must be 3 parts, and only numbers like 5.44.108
# It is best that 2'nd number is always 2 digits, eg at least 10
BUILDVERSION = 2.10.1

# Fixpack version
# Use this if you want to add extra chars (comments) to bldlevel
# ex RC3  GA  FIXPACK2 beta_47
# Comment out to avoid a fixpack line in bldlevel
#FIXPACK = RC1


